### ISSUE TITLE
Panic while creating Patch for diff on large repos

### ISSUE THREAD

**Issue by Ice3man543** [src-d/go-git#1106]
Hi, 
I created a program to fetch all commits and create diffs of all commits.

Here is the stacktrace - 

```
charsLen: 190640 text: 190640 lineArray: 64470
panic: runtime error: index out of range

goroutine 38 [running]:
github.com/sergi/go-diff/diffmatchpatch.(*DiffMatchPatch).DiffCharsToLines(0xc0ba281878, 0xc07d01c300, 0x49, 0x4a, 0xc0b8204000, 0xfbd6, 0x12800, 0x13000, 0xc07d01c300, 0x49)
	/home/ice3man/go/src/github.com/sergi/go-diff/diffmatchpatch/diff.go:455 +0x536
gopkg.in/src-d/go-git.v4/utils/diff.Do(0xc098928000, 0x50dceb, 0xc0a3aae000, 0x50e097, 0x0, 0x0, 0x2)
	/home/ice3man/go/src/gopkg.in/src-d/go-git.v4/utils/diff/diff.go:21 +0x1b4
gopkg.in/src-d/go-git.v4/plumbing/object.filePatchWithContext(0x8ed020, 0xc0000b0030, 0xc0493dd300, 0xc02dec0220, 0x2, 0x2, 0xc02dec0280)
	/home/ice3man/go/src/gopkg.in/src-d/go-git.v4/plumbing/object/patch.go:68 +0x220
gopkg.in/src-d/go-git.v4/plumbing/object.getPatchContext(0x8ed020, 0xc0000b0030, 0x0, 0x0, 0xc02dec1560, 0x4, 0x4, 0xc026374640, 0x0, 0xc001c2bab8)
	/home/ice3man/go/src/gopkg.in/src-d/go-git.v4/plumbing/object/patch.go:38 +0xd5
gopkg.in/src-d/go-git.v4/plumbing/object.Changes.PatchContext(0xc02dec1560, 0x4, 0x4, 0x8ed020, 0xc0000b0030, 0x4, 0x0, 0x0)
	/home/ice3man/go/src/gopkg.in/src-d/go-git.v4/plumbing/object/change.go:156 +0x62
gopkg.in/src-d/go-git.v4/plumbing/object.Changes.Patch(0xc02dec1560, 0x4, 0x4, 0x4, 0x4, 0x0)
	/home/ice3man/go/src/gopkg.in/src-d/go-git.v4/plumbing/object/change.go:148 +0x57
github.com/Ice3man543/gitpillage/pkg/clone.(*Agent).CloneCommits(0xc0000b45e0, 0xc0025cb8c0, 0xc000689b00, 0x30, 0x30, 0xc0025cb8c0)
	/home/ice3man/go/src/github.com/Ice3man543/gitpillage/pkg/clone/clone.go:79 +0x2dc
main.main.func2(0xc0000b0cf4, 0xc000090180, 0xc0000b45e0)
	/home/ice3man/go/src/github.com/Ice3man543/gitpillage/cmd/gitpillage/main.go:91 +0x55d
created by main.main
	/home/ice3man/go/src/github.com/Ice3man543/gitpillage/cmd/gitpillage/main.go:75 +0x264
```

I added a few `printf` statements where the crash was happening in order to get an idea of the issue. 

```go 
// DiffCharsToLines rehydrates the text in a diff from a string of line hashes to real lines of text.
func (dmp *DiffMatchPatch) DiffCharsToLines(diffs []Diff, lineArray []string) []Diff {
	hydrated := make([]Diff, 0, len(diffs))
	fmt.Printf("len: %d hydrated: %d\n", len(diffs), len(hydrated))
	for _, aDiff := range diffs {
		chars := aDiff.Text
		text := make([]string, len(chars))

		fmt.Printf("charsLen: %d text: %d lineArray: %d\n", len(chars), len(text), len(lineArray))

		for i, r := range chars {
			text[i] = lineArray[r]
		}

		aDiff.Text = strings.Join(text, "")
		hydrated = append(hydrated, aDiff)
	}
	return hydrated
}
```.

Here is the code i was using -
```go
for _, c := range commits {
		parentCommit, err := GetParentCommit(c, repo)
		if err != nil {
			parentCommit = c
		}

		commitTree, err := c.Tree()
		if err != nil {
			continue
		}

		parentCommitTree, err := parentCommit.Tree()
		if err != nil {
			continue
		}

		var changes object.Changes
		if parentCommit == c {
			changes, err = object.DiffTree(nil, parentCommitTree)
		} else {
			changes, err = object.DiffTree(parentCommitTree, commitTree)
		}
		if err != nil {
			continue
		}

		patch, err := changes.Patch()
		if err != nil {
			continue
		}
}
```

This is the repo - `INFO[0115] Cloning repo for user                         org=udacity repo=DandikUnited.github.io user=DandikUnited`

**Comment by zricethezav** [comment]
https://github.com/src-d/go-git/issues/973
https://github.com/sergi/go-diff/issues/89
