### ISSUE TITLE
Panic on packfile decode

### ISSUE THREAD

**Issue by euforia** [src-d/go-git#134]
I am seeing the panic below when trying to decode a packfile.  It looks like it's related to #130.  Would someone be able to confirm?  

Here's the calling snippet:

```
       packdec, err := packfile.NewDecoder(packfile.NewScanner(r.Body), objstore)
	if err != nil {
		return
	}
        // This is where it panics
	if _, err = packdec.Decode(); err != nil {
		return
	}
```

Here's the panic:

```http: panic serving 127.0.0.1:60648: runtime error: invalid memory address or nil pointer dereference
goroutine 82 [running]:
net/http.(*conn).serve.func1(0xc420212400)
	/Users/abs/.gvm/gos/go1.7.3/src/net/http/server.go:1491 +0x12a
panic(0x4d1c00, 0xc4200100d0)
	/Users/abs/.gvm/gos/go1.7.3/src/runtime/panic.go:458 +0x243
gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Decoder).recallByOffset(0xc4205cd9d0, 0x15ee, 0xc420214070, 0x60, 0xc47cb1f940, 0x0)
	/Users/abs/.gvm/pkgsets/go1.7.3/global/src/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/decoder.go:266 +0xce
gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Decoder).fillOFSDeltaObjectContent(0xc4205cd9d0, 0x7aa880, 0xc4202b8080, 0x15ee, 0x47fff8b4, 0x14, 0xc4207f9200)
	/Users/abs/.gvm/pkgsets/go1.7.3/global/src/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/decoder.go:242 +0xd9
gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Decoder).ReadObject(0xc4205cd9d0, 0x7aa880, 0xc4202b81c0, 0xce53f3af6349178b, 0xc5b353bb8b4c4f09)
	/Users/abs/.gvm/pkgsets/go1.7.3/global/src/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/decoder.go:164 +0x4ac
gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Decoder).readObjectsWithObjectStorer(0xc4205cd9d0, 0x61, 0xc4201ee010, 0x0)
	/Users/abs/.gvm/pkgsets/go1.7.3/global/src/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/decoder.go:110 +0x40
gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Decoder).doDecode(0xc4205cd9d0, 0x4a39c0, 0xc420014201)
	/Users/abs/.gvm/pkgsets/go1.7.3/global/src/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/decoder.go:94 +0xda
gopkg.in/src-d/go-git.v4/plumbing/format/packfile.(*Decoder).Decode(0xc4205cd9d0, 0x0, 0x0, 0x0, 0xc4202049f0, 0x1000)
	/Users/abs/.gvm/pkgsets/go1.7.3/global/src/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/decoder.go:74 +0x4a
github.com/euforia/gitchord/services.(*GitServer).ReceivePack(0xc4201fa000, 0x7a7180, 0xc42021c0d0, 0xc4200d23c0)
	/Users/abs/workbench/golang/src/github.com/euforia/gitchord/services/git.go:136 +0x8e0
github.com/euforia/gitchord/services.(*GitServer).ReceivePack-fm(0x7a7180, 0xc42021c0d0, 0xc4200d23c0)
	/Users/abs/workbench/golang/src/github.com/euforia/gitchord/cmd/gitchord/gitchord.go:99 +0x48
github.com/euforia/gitchord/services.(*Router).ServeHTTP(0xc420204000, 0x7a7180, 0xc42021c0d0, 0xc4200d22d0)
	/Users/abs/workbench/golang/src/github.com/euforia/gitchord/services/router.go:47 +0x755
net/http.serverHandler.ServeHTTP(0xc420212080, 0x7a7180, 0xc42021c0d0, 0xc4200d22d0)
	/Users/abs/.gvm/gos/go1.7.3/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420212400, 0x7a7a40, 0xc4202cc380)
	/Users/abs/.gvm/gos/go1.7.3/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/Users/abs/.gvm/gos/go1.7.3/src/net/http/server.go:2293 +0x44d
```

**Comment by mcuadros** [comment]
exactly, we are merging this ASAP

Thanks

**Comment by euforia** [comment]
thx for the quick response.
