### ISSUE TITLE
Fatal panic : Slice out of bounds

### ISSUE THREAD

**Issue by icambridge** [src-d/go-git#202]
I get this fatal panic. When getting the commits for https://github.com/vkbot/TrinityCore-1

```panic: runtime error: slice bounds out of range

goroutine 3093 [running]:
panic(0x773b60, 0xc42000c0f0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
gopkg.in/src-d/go-git.v4/plumbing/object.(*Signature).Decode(0xc42f9ecc58, 0xc42b74f065, 0x32, 0xf9b)
        /home/icambridge/golang/src/gopkg.in/src-d/go-git.v4/plumbing/object/object.go:93 +0x225
gopkg.in/src-d/go-git.v4/plumbing/object.(*Commit).Decode(0xc42f9ecc40, 0x98a900, 0xc4309fcb00, 0x0, 0x0)
        /home/icambridge/golang/src/gopkg.in/src-d/go-git.v4/plumbing/object/commit.go:147 +0x5c0
gopkg.in/src-d/go-git.v4/plumbing/object.DecodeCommit(0x6fe9c9844080, 0xc421f78330, 0x98a900, 0xc4309fcb00, 0x0, 0x0, 0xc42f4f41e0)
        /home/icambridge/golang/src/gopkg.in/src-d/go-git.v4/plumbing/object/commit.go:49 +0x9f
gopkg.in/src-d/go-git.v4/plumbing/object.(*CommitIter).Next(0xc430cdc060, 0xbc1909c6334e4c62, 0xc7d43224, 0xc42d6fb0a8)
        /home/icambridge/golang/src/gopkg.in/src-d/go-git.v4/plumbing/object/commit.go:250 +0x75
github.com/icambridge/techfinder/techfinder.GitRepository.Commits(0xc421f78390, 0xc421f78270, 0x2a, 0xc421f78210, 0x24, 0xc421f78240, 0x26, 0xc4225d1da0, 0x0, 0x0, ...)
        /home/icambridge/golang/src/github.com/icambridge/x.go:64 +0x138
```

**Comment by mcuadros** [comment]
fixed
