### ISSUE TITLE
ssh HostKeyCallback now required

### ISSUE THREAD

**Issue by adampointer** [src-d/go-git#328]
The ssh library has introduced a breaking change where HostKeyCallback is required in ClientConfig whereas before it's absence would simply disable verification altogether. When cloning a repository via SSH you now get this error:

`ssh: must specify HostKeyCallback`

I have forked this and written a very basic callback which will verify host keys against known_hosts. I do not expect my PR to be accepted as it is tbh as its kind of rubbish and needs more thought. But I thought it may be of some use to illustrate the problem.

**Comment by smola** [comment]
@adampointer Thanks! Your solutions seems the right one to me. You could add the following in a PR:

* Apply the same defaults to `ssh.Password` auth method.
* Document in PublicKeys/Password godoc that they use known_hosts.
* Make `clientConfig()` public in `ssh.AuthMethod`.

This way users would be able to easily override this behavior (for example, to use an in-memory map for their own custom known hosts).

**Comment by taralx** [comment]
For now can we put in a stub? Hard to contribute when the test is broken. :disappointed:

**Comment by mcuadros** [comment]
@taralx you can fix golang.org/x/crypto/ssh to a old version previous to this change. Or merge the PR on your local branch

**Comment by smola** [comment]
@taralx As stated in https://github.com/src-d/go-git/issues/332, we will change SSH tests to use a local server. If you want it to be implemented faster, PRs are welcome ;)

**Comment by kris-nova** [comment]
So running this new code, with the new defaults I am getting the following:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x139851a]

goroutine 1 [running]:
github.com/kris-nova/klone/vendor/golang.org/x/crypto/ssh.publicKeyCallback.auth(0x0, 0xc42017cc40, 0x20, 0x20, 0x0, 0x0, 0x1853260, 0xc420441080, 0x184cda0, 0xc420019500, ...)
	/go/src/github.com/kris-nova/klone/vendor/golang.org/x/crypto/ssh/client_auth.go:187 +0x3a
github.com/kris-nova/klone/vendor/golang.org/x/crypto/ssh.(*connection).clientAuthenticate(0xc420334a80, 0xc42015e240, 0x0, 0xa)
	/go/src/github.com/kris-nova/klone/vendor/golang.org/x/crypto/ssh/client_auth.go:36 +0x369
github.com/kris-nova/klone/vendor/golang.org/x/crypto/ssh.(*connection).clientHandshake(0xc420334a80, 0xc4201db750, 0xd, 0xc42015e240, 0x0, 0x0)
	/go/src/github.com/kris-nova/klone/vendor/golang.org/x/crypto/ssh/client.go:112 +0x2e6
github.com/kris-nova/klone/vendor/golang.org/x/crypto/ssh.NewClientConn(0x18570e0, 0xc42013a2e0, 0xc4201db750, 0xd, 0xc42015e180, 0x18570e0, 0xc42013a2e0, 0x0, 0x0, 0x14d7d00, ...)
	/go/src/github.com/kris-nova/klone/vendor/golang.org/x/crypto/ssh/client.go:82 +0xfa
github.com/kris-nova/klone/vendor/golang.org/x/crypto/ssh.Dial(0x15b5b87, 0x3, 0xc4201db750, 0xd, 0xc42015e180, 0xc4200cd408, 0x100ed4d, 0x152d360)
	/go/src/github.com/kris-nova/klone/vendor/golang.org/x/crypto/ssh/client.go:176 +0xb3
github.com/kris-nova/klone/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*command).connect(0xc4201d50e0, 0x1850e60, 0xc4201d2a00)
	/go/src/github.com/kris-nova/klone/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:98 +0xfc
github.com/kris-nova/klone/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*runner).Command(0x18a7660, 0x15bd98b, 0xf, 0x1856d80, 0xc42021f7d0, 0x1850e60, 0xc4201d2a00, 0x13cb0ae, 0x1504a20, 0xc4201141b0, ...)
	/go/src/github.com/kris-nova/klone/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:32 +0x9a
github.com/kris-nova/klone/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common.(*client).newSession(0xc420013bd0, 0x15bd98b, 0xf, 0x1856d80, 0xc42021f7d0, 0x1850e60, 0xc4201d2a00, 0x0, 0x1856d80, 0xc42021f7d0)
	/go/src/github.com/kris-nova/klone/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common/common.go:109 +0x96
github.com/kris-nova/klone/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common.(*client).NewUploadPackSession(0xc420013bd0, 0x1856d80, 0xc42021f7d0, 0x1850e60, 0xc4201d2a00, 0xc42021f7d0, 0x0, 0x0, 0x0)
	/go/src/github.com/kris-nova/klone/vendor/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common/common.go:86 +0x6f
github.com/kris-nova/klone/vendor/gopkg.in/src-d/go-git%2ev4.newUploadPackSession(0xc42021ee70, 0x21, 0x1850e60, 0xc4201d2a00, 0x1552220, 0x118dc6c, 0xc4201d29c0, 0x20)
	/go/src/github.com/kris-nova/klone/vendor/gopkg.in/src-d/go-git.v4/remote.go:183 +0xb3
github.com/kris-nova/klone/vendor/gopkg.in/src-d/go-git%2ev4.(*Remote).fetch(0xc4201d2200, 0xc4200cd7e8, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/kris-nova/klone/vendor/gopkg.in/src-d/go-git.v4/remote.go:134 +0x144
github.com/kris-nova/klone/vendor/gopkg.in/src-d/go-git%2ev4.(*Remote).Fetch(0xc4201d2200, 0xc4200cd7e8, 0x4, 0x1)
	/go/src/github.com/kris-nova/klone/vendor/gopkg.in/src-d/go-git.v4/remote.go:52 +0x35
github.com/kris-nova/klone/pkg/klone/kloners/golang.(*Kloner).AddRemote(0xc4201da0c0, 0x15b7b83, 0x6, 0x1857380, 0xc4201388d0, 0x1857380, 0xc4201388d0, 0xc4200cd8e8, 0x118eb46)
	/go/src/github.com/kris-nova/klone/pkg/klone/kloners/golang/klone.go:103 +0x64d
github.com/kris-nova/klone/pkg/klone.(*Kloneable).kloneAlreadyForked(0xc4200cdb70, 0x0, 0x0, 0x14d8740, 0xc4201da050)
	/go/src/github.com/kris-nova/klone/pkg/klone/klone_patterns.go:44 +0x17c
github.com/kris-nova/klone/pkg/klone.(*Kloneable).Klone(0xc4200cdb70, 0x38, 0xc4200cdc68, 0x4, 0x4)
	/go/src/github.com/kris-nova/klone/pkg/klone/kloneable.go:67 +0x85
github.com/kris-nova/klone/pkg/klone.Klone(0x7fff5fbffa1e, 0x4, 0x0, 0x0)
	/go/src/github.com/kris-nova/klone/pkg/klone/klone.go:87 +0x466
github.com/kris-nova/klone/cmd.glob..func1(0x1887a40, 0xc420013e20, 0x1, 0x1)
	/go/src/github.com/kris-nova/klone/cmd/root.go:43 +0x4a
github.com/kris-nova/klone/vendor/github.com/spf13/cobra.(*Command).execute(0x1887a40, 0xc42000c2f0, 0x1, 0x1, 0x1887a40, 0xc42000c2f0)
	/go/src/github.com/kris-nova/klone/vendor/github.com/spf13/cobra/command.go:651 +0x23a
github.com/kris-nova/klone/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1887a40, 0xc420074058, 0x0, 0x147a672)
	/go/src/github.com/kris-nova/klone/vendor/github.com/spf13/cobra/command.go:726 +0x339
github.com/kris-nova/klone/vendor/github.com/spf13/cobra.(*Command).Execute(0x1887a40, 0xc420077820, 0xc420114270)
	/go/src/github.com/kris-nova/klone/vendor/github.com/spf13/cobra/command.go:685 +0x2b
github.com/kris-nova/klone/cmd.Execute()
	/go/src/github.com/kris-nova/klone/cmd/root.go:54 +0x31
main.main()
	/go/src/github.com/kris-nova/klone/main.go:29 +0x20
```

**Comment by zsmagyar11** [comment]
I am getting the same error was working fine in previous builds but now broken.

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x847ca6]

goroutine 6 [running]:
testing.tRunner.func1(0xc420057c70)
	/usr/local/go/src/testing/testing.go:622 +0x29d
panic(0x9126c0, 0xc32640)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
git.illumina.com/ILS/Automation_GT_Uploader/vendor/golang.org/x/crypto/ssh.(*Client).NewSession(0x0, 0x0, 0xc4200960f0, 0x0)
	/go/src/git.illumina.com/ILS/Automation_GT_Uploader/vendor/golang.org/x/crypto/ssh/client.go:129 +0x26
git.illumina.com/ILS/Automation_GT_Uploader/helpers.(*SSHClient).newSession(0xc420131a40, 0x1, 0x1, 0x29)

**Comment by mcuadros** [comment]
Are you use the latest version?

**Comment by zsmagyar11** [comment]
I am using a 1.8.3 docker container pulling down the latest version of the crypto ssh package.

**Comment by mcuadros** [comment]
go-git version?

**Comment by zsmagyar11** [comment]
I don't know what you mean? Inside my 1.8.3 docker container I get down my repo which pulls crypto ssh as a vendored submodule.   git submodule update --init --recursive vendor/golang.org/x/crypto. This is running from jenkins.

On my machine where I haven't updated this library since april the same code runs (able to create a username/pw auth session)

**Comment by mcuadros** [comment]
I am asking about the tag or commit on the go-git code that you are using.

**Comment by zsmagyar11** [comment]
How can I find that out? presumed it was pulling down the latest commit each time from /golang.org/x/crypto

**Comment by Fale** [comment]
I'm experiencing the same panic problem with:

```$ go version
go version go1.8.3 linux/amd64
```

```
        {   
            "ImportPath": "golang.org/x/crypto/ssh",
            "Rev": "12c985af8526c1f6f0c463bbfd9d69623d13b323"
        },  
        {   
            "ImportPath": "golang.org/x/crypto/ssh/agent",
            "Rev": "12c985af8526c1f6f0c463bbfd9d69623d13b323"
        }   
```
