### ISSUE TITLE
ssh: handshake failed: knownhosts: key mismatch

### ISSUE THREAD

**Issue by DarkNightElves** [src-d/go-git#738]
I tried to write codes for cloning a repository via ssh protocol,  it failed with the error:
ssh: handshake failed: knownhosts: key mismatch

 my codes:

```
package main

import (
        "fmt"
        "os"

        git "gopkg.in/src-d/go-git.v4"
        ssh "gopkg.in/src-d/go-git.v4/plumbing/transport/ssh"
)

func main() {
        auth, err := ssh.NewPublicKeysFromFile("git", "/root/.ssh/id_rsa", "")
        fmt.Println(err)

        _, err2 := git.PlainClone("./dvue", false, &git.CloneOptions{
                URL:           "git@git.commd.io:work/LocalService.git",
                ReferenceName: "refs/head/master",
                Auth:          auth,
                Progress:      os.Stdout,
        })

        fmt.Println(err2)
}

```

When I tried the following command, it was all right. 
```
git clone git@git.commd.io:work/LocalService.git
```

**Comment by DarkNightElves** [comment]
Using the following codes,  no errors occured, but it just created a empty directory.

```
package main

import (
        "fmt"
        "os"

        "golang.org/x/crypto/ssh"
        "gopkg.in/src-d/go-git.v4"
        gitssh "gopkg.in/src-d/go-git.v4/plumbing/transport/ssh"
        "io/ioutil"
        "net"
)

func main() {
        s := fmt.Sprintf("%s/.ssh/id_rsa", os.Getenv("HOME"))
        sshKey, err := ioutil.ReadFile(s)
        signer, err := ssh.ParsePrivateKey([]byte(sshKey))

        hostKeyCallback := func(hostname string, remote net.Addr, key ssh.PublicKey) error {
                return nil
        }

        auth := &gitssh.PublicKeys{User: "git", Signer: signer, HostKeyCallbackHelper: gitssh.HostKeyCallbackHelper{
                HostKeyCallback: hostKeyCallback,
        }}

        _, err = git.PlainClone("./ccc", false, &git.CloneOptions{
                URL:           "git@git.commd.io:work/LocalService.git",
                Progress:      os.Stdout,
                Auth:          auth,
                ReferenceName: "refs/head/master",
        })

        fmt.Println(err)
}
```

**Comment by StanislavKH** [comment]
when trying to use code from example simply with my key and repository getting panic error 

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x713de4]

goroutine 1 [running]:
github.com/kevinburke/ssh_config.decode.func1(0xc4201236b0)
        /root/.go/src/github.com/kevinburke/ssh_config/config.go:216 +0x1f2
panic(0x790ea0, 0xa43f10)
        /usr/lib/go-1.10/src/runtime/panic.go:505 +0x229
github.com/kevinburke/ssh_config.(*sshParser).parseKV(0xc420072720, 0xc42015c7b0)
        /root/.go/src/github.com/kevinburke/ssh_config/parser.go:99 +0x264
github.com/kevinburke/ssh_config.(*sshParser).(github.com/kevinburke/ssh_config.parseKV)-fm(0xc42015c7b0)
        /root/.go/src/github.com/kevinburke/ssh_config/parser.go:80 +0x2a
github.com/kevinburke/ssh_config.(*sshParser).run(0xc420072720)
        /root/.go/src/github.com/kevinburke/ssh_config/parser.go:38 +0x42
github.com/kevinburke/ssh_config.parseSSH(0xc42008a300, 0xc420000000, 0xc42008a300)
        /root/.go/src/github.com/kevinburke/ssh_config/parser.go:180 +0x307
github.com/kevinburke/ssh_config.decode(0x858180, 0xc42000e650, 0xc420000000, 0x0, 0x0, 0x0)
        /root/.go/src/github.com/kevinburke/ssh_config/config.go:226 +0x90
github.com/kevinburke/ssh_config.parseWithDepth(0xc420029820, 0x11, 0x80da00, 0x0, 0x0, 0x0)
        /root/.go/src/github.com/kevinburke/ssh_config/config.go:198 +0xbe
github.com/kevinburke/ssh_config.parseFile(0xc420029820, 0x11, 0xc420123758, 0x429659, 0xc42006e0f0)
        /root/.go/src/github.com/kevinburke/ssh_config/config.go:189 +0x3a
github.com/kevinburke/ssh_config.(*UserSettings).GetStrict.func1()
        /root/.go/src/github.com/kevinburke/ssh_config/config.go:158 +0x53
sync.(*Once).Do(0xa49928, 0xc4201237e8)
        /usr/lib/go-1.10/src/sync/once.go:44 +0xbe
github.com/kevinburke/ssh_config.(*UserSettings).GetStrict(0xa49900, 0xc42002c0c4, 0x10, 0x810afe, 0x8, 0x2, 0x14, 0x0, 0x0)
        /root/.go/src/github.com/kevinburke/ssh_config/config.go:149 +0x50
github.com/kevinburke/ssh_config.(*UserSettings).Get(0xa49900, 0xc42002c0c4, 0x10, 0x810afe, 0x8, 0x0, 0x0)
        /root/.go/src/github.com/kevinburke/ssh_config/config.go:134 +0x57
gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*command).doGetHostWithPortFromSSHConfig(0xc42009af50, 0xc42015c680, 0x0, 0x0)
        /root/.go/src/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:155 +0x161
gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*command).getHostWithPort(0xc42009af50, 0xc42015f380, 0x0)
        /root/.go/src/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:134 +0x32
gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*command).connect(0xc42009af50, 0x859ee0, 0xc420095ec0)
        /root/.go/src/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:118 +0x8e
gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*runner).Command(0xc42000e5b8, 0x814389, 0xf, 0xc420072660, 0x859ee0, 0xc420095ec0, 0xc4200a7320, 0xc420072660, 0x0, 0xc420123b18)
        /root/.go/src/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:50 +0x9d
gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common.(*client).newSession(0xc42015c150, 0x814389, 0xf, 0xc420072660, 0x859ee0, 0xc420095ec0, 0x0, 0x0, 0xc420072660)
        /root/.go/src/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common/common.go:112 +0x89
gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common.(*client).NewUploadPackSession(0xc42015c150, 0xc420072660, 0x859ee0, 0xc420095ec0, 0xc420072660, 0x0, 0x0, 0xc42015c470)
        /root/.go/src/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common/common.go:89 +0x62
gopkg.in/src-d/go-git%2ev4.newUploadPackSession(0xc42002c0c0, 0x39, 0x859ee0, 0xc420095ec0, 0xc42006f940, 0x85dc80, 0xc420123c18, 0x411f38)
        /root/.go/src/gopkg.in/src-d/go-git.v4/remote.go:324 +0x9c
gopkg.in/src-d/go-git%2ev4.(*Remote).fetch(0xc420157e00, 0x85c200, 0xc4200220e8, 0xc420123db8, 0x0, 0x0, 0x0, 0x0)
        /root/.go/src/gopkg.in/src-d/go-git.v4/remote.go:262 +0x11b
gopkg.in/src-d/go-git%2ev4.(*Repository).fetchAndUpdateReferences(0xc4201721b0, 0x85c200, 0xc4200220e8, 0xc420123db8, 0x8166e0, 0x13, 0xc420157900, 0x0, 0x0)
        /root/.go/src/gopkg.in/src-d/go-git.v4/repository.go:548 +0xbf
gopkg.in/src-d/go-git%2ev4.(*Repository).clone(0xc4201721b0, 0x85c200, 0xc4200220e8, 0xc420107f80, 0x0, 0x0)
        /root/.go/src/gopkg.in/src-d/go-git.v4/repository.go:441 +0x251
gopkg.in/src-d/go-git%2ev4.PlainCloneContext(0x85c200, 0xc4200220e8, 0x80e10a, 0x5, 0x411f00, 0xc420107f80, 0x7f30c0, 0x1, 0xc420107f80)
        /root/.go/src/gopkg.in/src-d/go-git.v4/repository.go:322 +0xa5
gopkg.in/src-d/go-git%2ev4.PlainClone(0x80e10a, 0x5, 0x800, 0xc420107f80, 0xc4201578c0, 0x0, 0x0)
        /root/.go/src/gopkg.in/src-d/go-git.v4/repository.go:306 +0x60
main.main()
```

**Comment by pashh** [comment]
I met the same problem
 `sshAuth, err := gitssh.NewPublicKeysFromFile("git", "/home/pashh/.ssh/id_dsa", "")

        r, err := git.PlainClone("./wc", false, &git.CloneOptions{
                URL:               "git@gitlab.t-systems.ru/tvpp/portal.git",
                Auth:              sshAuth,
                Progress: os.Stdout,
        })

        check_err(err)`


and error:

`panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x629214]

goroutine 1 [running]:
github.com/kevinburke/ssh_config.decode.func1(0xc4200f76f8)
	/home/pashh/projects/go-lang/src/github.com/kevinburke/ssh_config/config.go:216 +0x1f2
panic(0x7966a0, 0xa4df30)
	/opt/golang/go/src/runtime/panic.go:502 +0x229
github.com/kevinburke/ssh_config.(*sshParser).parseKV(0xc4200ec5a0, 0xc42001e690)
	/home/pashh/projects/go-lang/src/github.com/kevinburke/ssh_config/parser.go:99 +0x264
github.com/kevinburke/ssh_config.(*sshParser).(github.com/kevinburke/ssh_config.parseKV)-fm(0xc42001e690)
	/home/pashh/projects/go-lang/src/github.com/kevinburke/ssh_config/parser.go:80 +0x2a
github.com/kevinburke/ssh_config.(*sshParser).run(0xc4200ec5a0)
	/home/pashh/projects/go-lang/src/github.com/kevinburke/ssh_config/parser.go:38 +0x42
github.com/kevinburke/ssh_config.parseSSH(0xc420083500, 0xc4200a0000, 0xc420083500)
	/home/pashh/projects/go-lang/src/github.com/kevinburke/ssh_config/parser.go:180 +0x307
github.com/kevinburke/ssh_config.decode(0x85f360, 0xc4200a0640, 0xc4200a0000, 0x0, 0x0, 0x0)
	/home/pashh/projects/go-lang/src/github.com/kevinburke/ssh_config/config.go:226 +0x90
github.com/kevinburke/ssh_config.parseWithDepth(0xc4200b7e00, 0x17, 0x814700, 0x0, 0x0, 0x0)
	/home/pashh/projects/go-lang/src/github.com/kevinburke/ssh_config/config.go:198 +0xbe
github.com/kevinburke/ssh_config.parseFile(0xc4200b7e00, 0x17, 0xc4200f77a0, 0x4293a9, 0xc4200a40b0)
	/home/pashh/projects/go-lang/src/github.com/kevinburke/ssh_config/config.go:189 +0x3a
github.com/kevinburke/ssh_config.(*UserSettings).GetStrict.func1()
	/home/pashh/projects/go-lang/src/github.com/kevinburke/ssh_config/config.go:158 +0x53
sync.(*Once).Do(0xa53988, 0xc4200f7830)
	/opt/golang/go/src/sync/once.go:44 +0xbe
github.com/kevinburke/ssh_config.(*UserSettings).GetStrict(0xa53960, 0xc42009a906, 0x13, 0x8177f1, 0x8, 0xc4200b7600, 0x1c, 0x0, 0x0)
	/home/pashh/projects/go-lang/src/github.com/kevinburke/ssh_config/config.go:149 +0x50
github.com/kevinburke/ssh_config.(*UserSettings).Get(0xa53960, 0xc42009a906, 0x13, 0x8177f1, 0x8, 0xc4200a31d0, 0xc4200f7928)
	/home/pashh/projects/go-lang/src/github.com/kevinburke/ssh_config/config.go:134 +0x57
gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*command).doGetHostWithPortFromSSHConfig(0xc4200a2f00, 0xc420178bd0, 0x0, 0x0)
	/home/pashh/projects/go-lang/src/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:155 +0x96
gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*command).getHostWithPort(0xc4200a2f00, 0xc4201756c0, 0x0)
	/home/pashh/projects/go-lang/src/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:134 +0x32
gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*command).connect(0xc4200a2f00, 0x861100, 0xc420097f80)
	/home/pashh/projects/go-lang/src/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:118 +0x8e
gopkg.in/src-d/go-git.v4/plumbing/transport/ssh.(*runner).Command(0xc4200a0510, 0x81b094, 0xf, 0xc4200ec4e0, 0x861100, 0xc420097f80, 0xc4200b9320, 0xc4200b9348, 0x1, 0xc4200f7b28)
	/home/pashh/projects/go-lang/src/gopkg.in/src-d/go-git.v4/plumbing/transport/ssh/common.go:50 +0x9d
gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common.(*client).newSession(0xc420093830, 0x81b094, 0xf, 0xc4200ec4e0, 0x861100, 0xc420097f80, 0x0, 0x0, 0xc4200ec4e0)
	/home/pashh/projects/go-lang/src/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common/common.go:112 +0x89
gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common.(*client).NewUploadPackSession(0xc420093830, 0xc4200ec4e0, 0x861100, 0xc420097f80, 0xc4200ec4e0, 0x0, 0x0, 0xc420178490)
	/home/pashh/projects/go-lang/src/gopkg.in/src-d/go-git.v4/plumbing/transport/internal/common/common.go:89 +0x62
gopkg.in/src-d/go-git%2ev4.newUploadPackSession(0xc42009a900, 0x29, 0x861100, 0xc420097f80, 0xc4200f7c18, 0x411c88, 0x20, 0x7b3440)
	/home/pashh/projects/go-lang/src/gopkg.in/src-d/go-git.v4/remote.go:321 +0x9c
gopkg.in/src-d/go-git%2ev4.(*Remote).fetch(0xc420171c80, 0x8634e0, 0xc42009e030, 0xc4200f7dd8, 0x0, 0x0, 0x0, 0x0)
	/home/pashh/projects/go-lang/src/gopkg.in/src-d/go-git.v4/remote.go:259 +0x12b
gopkg.in/src-d/go-git%2ev4.(*Repository).fetchAndUpdateReferences(0xc420186240, 0x8634e0, 0xc42009e030, 0xc4200f7dd8, 0x814806, 0x4, 0xc4200f7da0, 0x72962e, 0xc420186240)
	/home/pashh/projects/go-lang/src/gopkg.in/src-d/go-git.v4/repository.go:650 +0xbf
gopkg.in/src-d/go-git%2ev4.(*Repository).clone(0xc420186240, 0x8634e0, 0xc42009e030, 0xc4200d9f80, 0x0, 0x0)
	/home/pashh/projects/go-lang/src/gopkg.in/src-d/go-git.v4/repository.go:521 +0x251
gopkg.in/src-d/go-git%2ev4.PlainCloneContext(0x8634e0, 0xc42009e030, 0x81471a, 0x4, 0x411c00, 0xc4200d9f80, 0x7f9900, 0x1, 0xc4200d9f80)
	/home/pashh/projects/go-lang/src/gopkg.in/src-d/go-git.v4/repository.go:353 +0xa5
gopkg.in/src-d/go-git%2ev4.PlainClone(0x81471a, 0x4, 0x81f000, 0xc4200d9f80, 0x0, 0x0, 0xc420097f80)
	/home/pashh/projects/go-lang/src/gopkg.in/src-d/go-git.v4/repository.go:337 +0x60
main.main()
	/home/pashh/projects/go-lang/src/try.gogs.io/PGH/golang_examples/git_wc/main.go:37 +0x115
exit status 2
`

**Comment by pashh** [comment]
The reason of error
`panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x629214]`
is a absence of empty string in ~/.ssh/config
here is issue about it:
https://github.com/trntv/sshed/issues/5

**Comment by pashh** [comment]
I'm summarised all types auth for clone private repo examples here
https://github.com/src-d/go-git/pull/863
please point me out if I made something wrong

**Comment by inge4pres** [comment]
Seems a dupe of https://github.com/src-d/go-git/issues/637
