### ISSUE TITLE
runtime error: slice bounds out of range (nextPackData)

### ISSUE THREAD

**Issue by barnettZQG** [src-d/go-git#852]
```
runtime error: slice bounds out of range
goroutine 557650 [running]:
runtime/debug.Stack(0xc42000e018, 0xc433d4efa8, 0x1)
 /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
 /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/goodrain/rainbond/builder/exector.(*exectorManager).buildFromSourceCode.func1.1(0xc435d82160)
 /go/src/github.com/goodrain/rainbond/builder/exector/exector.go:193 +0x83
panic(0xec1bc0, 0x1793550)
 /usr/local/go/src/runtime/panic.go:489 +0x2cf
bytes.(*Buffer).Write(0xc432aeaf50, 0xc433416b41, 0x29, 0x80, 0x29, 0x0, 0x0)
 /usr/local/go/src/bytes/buffer.go:138 +0xc9
github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/sideband.(*Demuxer).nextPackData(0xc4208766e0, 0x0, 0x0, 0x0, 0x0, 0x0)
 /go/src/github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/sideband/demux.go:127 +0x10f
github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/sideband.(*Demuxer).doRead(0xc4208766e0, 0xc430ede000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
 /go/src/github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/sideband/demux.go:83 +0x2f
github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/sideband.(*Demuxer).Read(0xc4208766e0, 0xc430ede000, 0x8000, 0x8000, 0x8000, 0x8000, 0x0)
 /go/src/github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git.v4/plumbing/protocol/packp/sideband/demux.go:71 +0x77
io.copyBuffer(0x7f8249624ab8, 0xc4202efdc0, 0x17a8980, 0xc4208766e0, 0xc430ede000, 0x8000, 0x8000, 0xf592a0, 0xc433d4f300, 0x7f8249624ab8)
 /usr/local/go/src/io/io.go:390 +0x100
io.Copy(0x7f8249624ab8, 0xc4202efdc0, 0x17a8980, 0xc4208766e0, 0xc4202efdc0, 0xc433d4f370, 0x40f4fd)
 /usr/local/go/src/io/io.go:360 +0x68
github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.writePackfileToObjectStorage(0x7f8249624a10, 0xc42f24f7a0, 0x17a8980, 0xc4208766e0, 0x0, 0x0)
 /go/src/github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/common.go:51 +0x13b
github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile.UpdateObjectStorage(0x7f8249913478, 0xc42f24f7a0, 0x17a8980, 0xc4208766e0, 0xc42f24f7a0, 0x1)
 /go/src/github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git.v4/plumbing/format/packfile/common.go:30 +0x344
github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git%2ev4.(*Remote).fetchPack(0xc433613620, 0x17b6480, 0xc42f24ed20, 0xc433d4f6e0, 0x17b52c0, 0xc4205d8050, 0xc42c891140, 0x0, 0x0)
 /go/src/github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git.v4/remote.go:366 +0x2f9
github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git%2ev4.(*Remote).fetch(0xc433613620, 0x17b6480, 0xc42f24ed20, 0xc433d4f6e0, 0x0, 0x0, 0x0, 0x0)
 /go/src/github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git.v4/remote.go:301 +0x70e
github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git%2ev4.(*Repository).fetchAndUpdateReferences(0xc4344ba660, 0x17b6480, 0xc42f24ed20, 0xc433d4f6e0, 0xc42f0695b0, 0xf, 0xc4336123c0, 0x0, 0x0)
 /go/src/github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git.v4/repository.go:548 +0xbf
github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git%2ev4.(*Repository).clone(0xc4344ba660, 0x17b6480, 0xc42f24ed20, 0xc432aeafc0, 0x0, 0x0)
 /go/src/github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git.v4/repository.go:447 +0x25b
github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git%2ev4.PlainCloneContext(0x17b6480, 0xc42f24ed20, 0xc42cced200, 0x5d, 0x0, 0xc432aeafc0, 0xc4344ba390, 0x0, 0x0)
 /go/src/github.com/goodrain/rainbond/vendor/gopkg.in/src-d/go-git.v4/repository.go:322 +0xa5
github.com/goodrain/rainbond/builder/sources.GitClone(0xc433d64608, 0x0, 0xc43388e3f1, 0x2d, 0xc433d6460b, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
 /go/src/github.com/goodrain/rainbond/builder/sources/git.go:154 +0x1c9d
github.com/goodrain/rainbond/builder/sources.GitCloneOrPull(0xc433d64608, 0x0, 0xc43388e3f1, 0x2d, 0xc433d6460b, 0x4, 0x0, 0x0, 0x0, 0x0, ...)
 /go/src/github.com/goodrain/rainbond/builder/sources/git.go:377 +0x3c7
github.com/goodrain/rainbond/builder/exector.(*SourceCodeBuildItem).Run(0xc435d82160, 0x1a3185c5000, 0xc435d82160, 0x17b9f00)
 /go/src/github.com/goodrain/rainbond/builder/exector/build_from_sourcecode_run.go:134 +0x1bd
github.com/goodrain/rainbond/builder/exector.(*exectorManager).buildFromSourceCode.func1(0xc435d82160, 0xc433d64a20)
 /go/src/github.com/goodrain/rainbond/builder/exector/exector.go:198 +0x110
created by github.com/goodrain/rainbond/builder/exector.(*exectorManager).buildFromSourceCode
 /go/src/github.com/goodrain/rainbond/builder/exector/exector.go:217 +0x1b9
```

**Comment by smola** [comment]
@barnettZQG Any further information? Could you share an URL to a failing repository? What is the protocol being used for that URL?

**Comment by smola** [comment]
@barnettZQG Which protocol? `https://`? `git://`? `ssh://`? Do you have any example URL?
